#!/usr/bin/env python3
# client.py
# A command-line client to interact with the AuraOS daemon.
# v6: Now multi-lingual. It can execute both shell and Python scripts
#     generated by the AI, and still features auto-approval and retries.

import requests
import sys
import os
import subprocess
import tempfile

DAEMON_URL = "http://127.0.0.1:5000"
MAX_RETRIES = 2

DANGEROUS_KEYWORDS = [
    'rm ', 'sudo ', 'mv ', 'mkfs', '> /dev/', 'dd ', 'chmod ', 'chown '
]

def get_open_windows():
    """Uses wmctrl to get a list of open window titles."""
    try:
        result = subprocess.run(['wmctrl', '-l'], capture_output=True, text=True, check=True)
        windows = [line.split(maxsplit=3)[3] for line in result.stdout.strip().split('\n') if len(line.split(maxsplit=3)) == 4]
        return windows
    except (FileNotFoundError, subprocess.CalledProcessError):
        return []

def is_script_safe(script, script_type):
    """Checks if the script is safe. All Python scripts require confirmation for now."""
    if script_type == 'python':
        return False # Safety first: always confirm Python scripts.
    return not any(keyword in script for keyword in DANGEROUS_KEYWORDS)

def execute_script(script, script_type, display_var):
    """Executes a script based on its type."""
    if script_type == 'python':
        # Create a temporary file to run the python script
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as tmp_file:
            tmp_file.write(script)
            script_filename = tmp_file.name
        
        print(f"[*] Running Python script: {script_filename}")
        command = ['python3', script_filename]
        env = os.environ.copy()
    else: # shell script
        command = script
        env = os.environ.copy()
        if display_var:
            env['DISPLAY'] = display_var

    result = subprocess.run(command, shell=(script_type=='shell'), capture_output=True, text=True, check=False, env=env)
    
    if script_type == 'python':
        os.remove(script_filename) # Clean up the temporary file
        
    return result

def autonomous_workflow(intent):
    """The main workflow, now handling multiple script types."""
    original_intent = intent
    retries = 0
    
    while retries <= MAX_RETRIES:
        print("\n" + "#"*60)
        if retries > 0: print(f"[*] This is retry attempt {retries}/{MAX_RETRIES}.")
        else: print(f"[*] Sending intent to daemon: '{intent}'")

        # 1. Generate the script
        current_directory = os.getcwd()
        open_windows = get_open_windows()
        payload = {"intent": intent, "context": {"cwd": current_directory, "windows": open_windows}}
        
        try:
            response = requests.post(f"{DAEMON_URL}/generate_script", json=payload)
            response.raise_for_status()
            data = response.json()
        except requests.exceptions.RequestException as e:
            print(f"\n[!] Error connecting to daemon: {e}"); return

        if "error" in data:
            print(f"\n[!] AI could not generate script: {data['error']}"); return

        script = data.get("script")
        script_type = data.get("script_type", "shell") # Default to shell for safety
        if not script:
            print("\n[!] Daemon returned an empty script."); return

        # 2. Confirm or Auto-Approve
        print("\n" + "="*50)
        print(f"AI has generated the following '{script_type}' script to execute:")
        print(f"\n{script}\n")
        print("="*50)
        
        if is_script_safe(script, script_type):
            print("[+] Script is considered safe. Auto-executing...")
        else:
            prompt_msg = "DANGEROUS KEYWORD DETECTED" if script_type == 'shell' else "PYTHON SCRIPT REQUIRES APPROVAL"
            confirm = input(f"{prompt_msg}. Execute this script? (y/n): ").lower()
            if confirm != 'y':
                print("\n[*] Execution cancelled by user."); return

        # 3. Execute the script
        print("\n[*] Executing script...")
        try:
            display_var = os.environ.get('DISPLAY')
            result = execute_script(script, script_type, display_var)
            
            print("\n--- Execution Result ---")
            print(f"Status: {'success' if result.returncode == 0 else 'error'}")
            if result.stdout: print(f"Output:\n{result.stdout}")
            
            # 4. Handle results (Success or Retry)
            if result.returncode == 0:
                print("\n[SUCCESS] Task completed successfully."); return
            else:
                error_output = result.stderr
                print(f"\n[FAILURE] Script failed to execute. Error:\n{error_output}")
                retries += 1
                if retries <= MAX_RETRIES:
                    intent = f"The original goal was '{original_intent}'. The last '{script_type}' script '{script}' failed with the error: {error_output}. Please provide a new, corrected script to achieve the original goal."
                else:
                    print("[!] Max retries reached. Aborting.")

        except Exception as e:
            print(f"\n[!] An unexpected error occurred during execution: {e}"); return

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: ai \"Your command for the AI\""); sys.exit(1)
    
    user_intent = " ".join(sys.argv[1:])
    autonomous_workflow(user_intent)
